---
name: microgateway
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: microgateway
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.1.0/24
    reserved: [10.244.1.1]
    static: [10.244.1.2,10.244.1.6,10.244.1.10]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: hello_world_spring
  templates:
  - name: hello_world_spring
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.1.6
  properties: {
    port: 8080
  }

- name: microgateway
  templates:
  - name: microgateway
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.1.2
  properties: {
    port: 8000,
    org: org,
    env: env,
    username: orgadmin,
    password: orgpassword,
    cluster_processes: 2
  }
